# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      # - freebsd
      # - windows # may reenable later
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^bump'
brew:
  # Reporitory to push the tap to.
  github:
    owner: jesseduffield
    name: homebrew-lazydocker

  # Your app's homepage.
  # Default is empty.
  homepage: 'https://github.com/jesseduffield/lazydocker/'

  # Your app's description.
  # Default is empty.
  description: 'A simple terminal UI for docker, written in Go'
